---
name: Test workflow (test)

on:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    environment: test
    env:
      DB_NAME: postgres
      DB_HOST: localhost
      DB_USERNAME: admin
      DB_PASSWORD: password
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Node 22
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run required containers
        run: docker compose -f docker-compose.test.yml up -d

      - name: Install dependencies
        run: npm ci --include=dev

      - name: Run migrations
        run: npx db-migrate up

      - name: Run linter
        run: npm run format

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test:cov
